services:
- type: web
  name: alx-travel-app
  env: docker
  plan: free
  rootDir: .
  healthCheckPath: /
  envVars:
  - key: DJANGO_SECRET_KEY
    generateValue: true
  - key: DEBUG
    value: "0"
  - key: ALLOWED_HOSTS
    value: alx-travel-app.onrender.com
  - key: CSRF_TRUSTED_EXTRA
    value: https://alx-travel-app.onrender.com
  - key: CELERY_BROKER_URL
    fromService:
      type: keyvalue
      name: travel-redis
      property: connectionString
  - key: CELERY_RESULT_BACKEND
    fromService:
      type: keyvalue
      name: travel-redis
      property: connectionString
  - key: EMAIL_HOST
    value: sandbox.smtp.mailtrap.io
  - key: EMAIL_PORT
    value: "587"
  - key: EMAIL_HOST_USER
    sync: false
  - key: EMAIL_HOST_PASSWORD
    sync: false
  - key: DEFAULT_FROM_EMAIL
    value: noreply@alx-travel.local

- type: worker
  name: alx-travel-celery
  env: docker
  rootDir: .
  plan: free
  # startCommand is removed because it's handled by the Dockerfile's CMD/ENTRYPOINT
  envVars:
  - key: DJANGO_SECRET_KEY
    sync: false
  - key: DEBUG
    value: "0"
  - key: CELERY_BROKER_URL
    fromService:
      type: keyvalue
      name: travel-redis
      property: connectionString
  - key: CELERY_RESULT_BACKEND
    fromService:
      type: keyvalue
      name: travel-redis
      property: connectionString
  - key: EMAIL_HOST
    value: sandbox.smtp.mailtrap.io
  - key: EMAIL_PORT
    value: "587"
  - key: EMAIL_HOST_USER
    sync: false
  - key: EMAIL_HOST_PASSWORD
    sync: false
  - key: DEFAULT_FROM_EMAIL
    value: noreply@alx-travel.local

- type: keyvalue
  name: travel-redis
  plan: free
  # Add the IP allow list for connections within Render's private network
  ipAllowList:
  - source: 0.0.0.0/0
    description: "Allow all IPs to connect (for demonstration)"